org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# Use AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Enable caching and parallelism for faster CI builds
org.gradle.caching=true
org.gradle.parallel=true
# android.newDsl=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
