// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCikUkPWIudOzaDdd0zG0o2HWuzxRN-B5U',
    appId: '1:313973393470:web:e9951c9e71d626d5e7e96f',
    messagingSenderId: '313973393470',
    projectId: 'mymus-pro',
    authDomain: 'mymus-pro.firebaseapp.com',
    storageBucket: 'mymus-pro.appspot.com',
    measurementId: 'G-KT99XL8VVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCVfcKEKER5UdoIVoUn36TeNmCc0Inhqw',
    appId: '1:313973393470:android:3e6d8689c6d1ed21e7e96f',
    messagingSenderId: '313973393470',
    projectId: 'mymus-pro',
    storageBucket: 'mymus-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOULIioOBh7-AmaUj9o3dtxxvzz_peSCY',
    appId: '1:313973393470:ios:20ec58b6544257cee7e96f',
    messagingSenderId: '313973393470',
    projectId: 'mymus-pro',
    storageBucket: 'mymus-pro.appspot.com',
    iosBundleId: 'com.detatech.muslim',
  );
}
